stages:
    - test

test:
    type: test
    script:
    - pip install virtualenv
    - virtualenv ./ENV
    - source ./ENV/bin/activate
    - pip install -r requirements.txt
    - pwd >> ./ENV/lib/python2.7/site-packages/v.pth
    - whoami
    - nosetests -s
    - deactivate